// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoMarket.Data;

namespace YoMarket.Migrations
{
    [DbContext(typeof(EshopContext))]
    [Migration("20230809193024_SeedDtaMig")]
    partial class SeedDtaMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projects.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripton = "مکمل ورزشی کراتین مونوهیدرات",
                            Name = "کراتین"
                        },
                        new
                        {
                            Id = 2,
                            Descripton = "انواع پروتئین نظیر پروتئین وی ,کازئین , ام پی سی",
                            Name = "پروتئین"
                        },
                        new
                        {
                            Id = 3,
                            Descripton = "انواع گینر های مس و ویت با طعم های مختلف",
                            Name = "گینر"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
